### ISSUE TITLE
While run obscreen.py file on Linux system it will show Internal Server Error.

### ISSUE THREAD

**Issue by ShubhamGhait** [jr-k/obscreen#102]
While implement  repo. on RPI is running well.
 But in case while run the obscreen.py file in my system, it will throw error  as below attached file.
 In this path of "/data/www/favicon.ico" same location as in original repository.
 Kindly give the solution where I'am wrong.

 
 python3 obscreen.py 
INFO:root:[obscreen-studio] Starting application v1.22.0...
INFO:waitress:Serving on http://0.0.0.0:5000
ERROR:src.service.WebServer:Exception on / [GET]
Traceback (most recent call last):
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/shubhamghait/signage/obscreen/src/controller/PlayerController.py", line 91, in player
    return render_template(
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: player/player.jinja.html
ERROR:src.service.WebServer:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/shubhamghait/signage/obscreen/src/controller/CoreController.py", line 22, in favicon
    return send_file("{}/favicon.ico".format(self.get_web_folder()), mimetype='image/x-icon')
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/flask/helpers.py", line 504, in send_file
    return werkzeug.utils.send_file(  # type: ignore[return-value]
  File "/home/shubhamghait/signage/obscreen/venv/lib/python3.8/site-packages/werkzeug/utils.py", line 428, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/data/www/favicon.ico'

**Comment by jr-k** [comment]
@ShubhamGhait Could you try with this new release please https://github.com/jr-k/obscreen/releases/tag/v2.0.0 ? Thanks
