### ISSUE TITLE
Update error 

### ISSUE THREAD

**Issue by GrLinkDn** [jr-k/obscreen#128]
After update by button on wide install:

`journalctl -u obscreen-studio -f
`
```
ago 05 10:30:33 obscreen-deb systemd[1]: Starting obscreen-studio.service - Obscreen Studio...
ago 05 10:30:33 obscreen-deb sudo[1130]:     root : PWD=/root/obscreen ; USER=root ; COMMAND=/usr/bin/systemctl restart obscreen-player.service
ago 05 10:30:33 obscreen-deb sudo[1130]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
ago 05 10:30:33 obscreen-deb sudo[1130]: pam_unix(sudo:session): session closed for user root
ago 05 10:30:33 obscreen-deb sudo[1128]: pam_unix(sudo:session): session closed for user root
ago 05 10:30:33 obscreen-deb systemd[1]: Started obscreen-studio.service - Obscreen Studio.
ago 05 10:30:34 obscreen-deb python[1127]: Traceback (most recent call last):
ago 05 10:30:34 obscreen-deb python[1127]:   File "/root/obscreen/obscreen.py", line 4, in <module>
ago 05 10:30:34 obscreen-deb python[1127]:     from src.Application import Application
ago 05 10:30:34 obscreen-deb python[1127]:   File "/root/obscreen/src/Application.py", line 7, in <module>
ago 05 10:30:34 obscreen-deb python[1127]:     from src.service.PluginStore import PluginStore
ago 05 10:30:34 obscreen-deb python[1127]:   File "/root/obscreen/src/service/PluginStore.py", line 12, in <module>
ago 05 10:30:34 obscreen-deb python[1127]:     from src.service.WebServer import WebServer
ago 05 10:30:34 obscreen-deb python[1127]:   File "/root/obscreen/src/service/WebServer.py", line 8, in <module>
ago 05 10:30:34 obscreen-deb python[1127]:     from flask_restx import Api
ago 05 10:30:34 obscreen-deb python[1127]: ModuleNotFoundError: No module named 'flask_restx'
ago 05 10:30:34 obscreen-deb systemd[1]: obscreen-studio.service: Main process exited, code=exited, status=1/FAILURE
ago 05 10:30:34 obscreen-deb systemd[1]: obscreen-studio.service: Failed with result 'exit-code'.
```

**Comment by GrLinkDn** [comment]
I solve with new install.

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/blob/master/docs/setup-run-on-rpi.md#or-system-wide
