### ISSUE TITLE
[Bug] Setting 'External url' returns 500 Internal Server Error

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#14]
After setting the correct 'external url' in the Settings, Error 500 Internal Server Error is displayed:

```
ERROR:src.service.WebServer:Exception on /settings/variable/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/controller/SettingsController.py", line 15, in settings_variable_list
    return render_template(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/views/settings/list.jinja.html", line 1, in top-level template code
    {% extends 'base.jinja.html' %}
  File "/app/views/base.jinja.html", line 80, in top-level template code
    {% block page %}
  File "/app/views/settings/list.jinja.html", line 21, in block 'page'
    {% include 'settings/component/table.jinja.html' %}
  File "/app/views/settings/component/table.jinja.html", line 37, in top-level template code
    {{ variable.display() }}
  File "/app/src/model/entity/Variable.py", line 130, in display
    for selectable in self.selectables:
TypeError: 'NoneType' object is not iterable
2024-05-03 22:58:43,985 - ERROR - Exception on /settings/variable/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/controller/SettingsController.py", line 15, in settings_variable_list
    return render_template(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/views/settings/list.jinja.html", line 1, in top-level template code
    {% extends 'base.jinja.html' %}
  File "/app/views/base.jinja.html", line 80, in top-level template code
    {% block page %}
  File "/app/views/settings/list.jinja.html", line 21, in block 'page'
    {% include 'settings/component/table.jinja.html' %}
  File "/app/views/settings/component/table.jinja.html", line 37, in top-level template code
    {{ variable.display() }}
  File "/app/src/model/entity/Variable.py", line 130, in display
    for selectable in self.selectables:
TypeError: 'NoneType' object is not iterable
INFO:werkzeug:172.22.0.2 - - [03/May/2024 22:58:43] "GET /settings/variable/list HTTP/1.1" 500 -
2024-05-03 22:58:43,986 - INFO - 172.22.0.2 - - [03/May/2024 22:58:43] "GET /settings/variable/list HTTP/1.1" 500 - 
```

The application continues to work, the manage page is still accessible, only the Settings page keeps returning 500 Internal Server Error after trying to set the external URL. This setting was properly working prior to version 1.5

Thank you

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.7
