### ISSUE TITLE
[Bug] Can no longer add pictures in v1.10 and v1.11 - Internal Server Error

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#35]
In v.1.10 and v.1.11 it is no longer possible to add pictures. An Internal Server Error message is displayed. The following error is shown in the container logs:

```
 ERROR:src.service.WebServer:Exception on /slideshow/slide/add [POST]
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
     rv = self.dispatch_request()
 2024-05-09 20:58:59,569 - ERROR - Exception on /slideshow/slide/add [POST]
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
   File "/app/src/controller/SlideshowController.py", line 64, in slideshow_slide_add
     self._model_store.slide().add_form(slide)
   File "/app/src/manager/SlideManager.py", line 116, in add_form
     self._db.add(form)
   File "/usr/local/lib/python3.9/site-packages/pysondb/db.py", line 107, in add
     raise UnknownKeyError(
 pysondb.errors.UnknownKeyError: Unrecognized / missing key(s) {'is_editable'}(Either the key(s) does not exists in the DB or is missing in the given data)
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
   File "/app/src/controller/SlideshowController.py", line 64, in slideshow_slide_add
     self._model_store.slide().add_form(slide)
   File "/app/src/manager/SlideManager.py", line 116, in add_form
     self._db.add(form)
   File "/usr/local/lib/python3.9/site-packages/pysondb/db.py", line 107, in add
     raise UnknownKeyError(
 pysondb.errors.UnknownKeyError: Unrecognized / missing key(s) {'is_editable'}(Either the key(s) does not exists in the DB or is missing in the given data)
```

Additionally, when trying to add a picture, the "Browse" button to select the file is no longer there. It now shows a text field named 'Object':
![afbeelding](https://github.com/jr-k/obscreen/assets/1370857/338a829f-439c-4b26-9c16-acd1d9f2fe2d)
Toggling from Picture to Video and back to Picture in the drop-down menu makes the 'Browse' button reappear, but then the Internal Server Error shown above appears.

This is/was working in v.1.9

Thank you

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.11 

(I've decided to replace version 1.11 with a fixed one, tell me if it's working now)
