### ISSUE TITLE
[Bug] Internal Server Error 500 upon activating User Authentication Module (v1.12)

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#45]
I've just pulled the latest version (v1.12) but the user authentication module does not work. Obscreen throws an Internal Server Error 500 after activating it via the GUI. The entire application is inaccessible afterwards.

```
2024-05-12 18:50:19,811 - ERROR - Exception on /settings/variable/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
ERROR:src.service.WebServer:Exception on /settings/variable/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/controller/SettingsController.py", line 16, in settings_variable_list
    return render_template(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/views/settings/list.jinja.html", line 1, in top-level template code
    {% extends 'base.jinja.html' %}
  File "/app/views/base.jinja.html", line 40, in top-level template code
    {% block header %}
  File "/app/views/base.jinja.html", line 67, in block 'header'
    <a href="{{ url_for('auth_user_list') }}">
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth_user_list'. Did you mean 'player_playlist' instead?
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/controller/SettingsController.py", line 16, in settings_variable_list
    return render_template(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/views/settings/list.jinja.html", line 1, in top-level template code
    {% extends 'base.jinja.html' %}
  File "/app/views/base.jinja.html", line 40, in top-level template code
    {% block header %}
  File "/app/views/base.jinja.html", line 67, in block 'header'
    <a href="{{ url_for('auth_user_list') }}">
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth_user_list'. Did you mean 'player_playlist' instead?
```

**Comment by jr-k** [comment]
Yeah sadly, i'm on it, thanks

**Comment by jr-k** [comment]
@Freekers Can you test this new v1.12 please ? :) Thanks 🙏

**Comment by Freekers** [comment]
Thanks, I've tested the new build. I'm now able to enable the authentication module and create a new user, but I cannot logout. It throws another 500 Internal Server Error while trying to logout

```
ERROR:src.service.WebServer:Exception on /logout [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/controller/AuthController.py", line 41, in logout
    logout_user()
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 213, in logout_user
    user = _get_user()
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
AttributeError: 'Flask' object has no attribute 'login_manager'
2024-05-12 19:44:36,031 - ERROR - Exception on /logout [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/controller/AuthController.py", line 41, in logout
    logout_user()
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 213, in logout_user
    user = _get_user()
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
AttributeError: 'Flask' object has no attribute 'login_manager'
```

**Comment by jr-k** [comment]
@Freekers  Here we go with cursed version 1.12 again 🥲, please give it a try and bring me some good news 👍
Thanks

**Comment by Freekers** [comment]
@jr-k Thanks, I repulled 1.12 again and it seems to work now. Thank you very much.

However, I do have some follow up questions/requests if you don't mind :)
1. What is the secret key (env var) currently used for? It seems redundant to me now that we can set username and password from the GUI.
2. It would be nice if the currently logged in user was displayed somewhere in the GUI at all times, for example top left/right or in the footer
3. It would be nice if behind every slide was mentioned which user uploaded the slide (for audit logging).

Thank you

**Comment by jr-k** [comment]
1. Secret key is used by internal web server to improve security of the authentication system. (Flask use a secret key that will be used for securely signing the session cookie). If you don't care about attack, just use default key "ANY_SECRET_KEY_HERE"
2. Yes of course
3. I agree

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.13

**Comment by Yakouao** [comment]
👍 Thanks a lot, version 1.13 seems to work except for youtube video that are not displaying... :( (Video Not Available)

I'm now going to test the fleet screen management.

**Comment by jr-k** [comment]
@Yakouao, YouTube is working on my side. Can you copy and paste the URL from the "Location" input field here? Please use code markdown in your reply so that the URL isn't altered by GitHub's markdown processor.

Regarding your questions:
1. Obscreen does not detect whether you have a reverse proxy; it only recognizes local URLs. However, sometimes Obscreen might need to generate external URLs, such as for slide previews (when you click the eye icon for exemple).
2. The Fleetmode screen restart plugin is a minimalistic tool designed to help developers understand how plugins function. As a demonstration, it adds a "Restart" button to the fleet view page (http://localhost:5000/fleet). In this mode, the menu is hidden. Previously, I did not implement hot reloading, so you had to restart the server when adding a slide. With this plugin, you now have a button that restarts the server for each device. Although it's no longer necessary, it remains useful for developers to kickstart a plugin easily. 

Restart is not working while running in docker environment. I'll delete that feature soon and will find a better feature to showcase a plugin.

**Comment by Yakouao** [comment]
This is the url from location input field : `https://www.youtube.com/watch?v=I_izvAbhExY` and when i click the eye it give me error 404 not found with this url `http://192.168.3.100:5000/I_izvAbhExY`

Thanks

**Comment by Yakouao** [comment]
I run this project on RPI 3 (Raspian os lite 64b) thru ssh with docker-compose. 
And i made the tests over web browser.

The rpi is connected to a screen thru HDMI and I just noticed that the rpi does not automatically start the slideshow on this screen...

How to make it autostart ? What did i miss ?

Thanks again

**Comment by jr-k** [comment]
@Yakouao I think we've found the culprit. Raspbian 'LITE' does not include a GUI (Graphical User Interface). You need to use the "Raspberry Pi OS with desktop"

**Comment by Yakouao** [comment]
Really sorry... my bad. :(
And i suppose it is the reason why the autostart file was not present ?

So i go with the desktop version.

Many thanks and sorry again.

**Comment by jr-k** [comment]
@Yakouao The file may not exist, since version 1.12 I log the command to create the file and clean everything if you've launched docker container before creating the file. I can't create the file automatically for you with docker since the file must be present in the raspberrypi system itself (on docker host). After first login just do `touch /home/pi/.config/lxsession/LXDE-pi/autostart` and then run docker container.

Are you alright with youtube now ?

**Comment by Yakouao** [comment]
So i try with the desktop version (raspian 64 bit desktop with ssh activated), here all the command  : 

curl -sSL https://get.docker.com | sh
sudo usermod -aG docker $(whoami)
logout

login again and :

mkdir -p obscreen/data/db obscreen/data/uploads && cd obscreen
sudo mkdir -p /home/pi/.config/lxsession/LXDE-pi 
sudo touch /home/pi/.config/lxsession/LXDE-pi/autostart
curl https://raw.githubusercontent.com/jr-k/obscreen/master/docker-compose.yml > docker-compose.yml
docker compose up --detach --pull always

No error return and the slideshow is visible from a webbrowser but the RPI boot on desktop.... :(

For youtube, it is the same than before 👍 

1. i create a slide youtube and enter in location an url like `https://www.youtube.com/watch?v=I_izvAbhExY`
2. just after i edit the slide and in location i find this : `https://www.youtube.com/watch?v=https://www.youtube.com/watch?v=I_izvAbhExY`
So eyes icon or slideshow don't play the video
3. If i reedit the slide and give the correct url : `https://www.youtube.com/watch?v=I_izvAbhExY` the eye icon work but not the slideshow

**Comment by Freekers** [comment]
> I can't create the file automatically for you with docker since the file must be present in the raspberrypi system itself (on docker host). After first login just do `touch /home/pi/.config/lxsession/LXDE-pi/autostart` and then run docker container.

@jr-k Is it possible to re-add the 'dummy' file to the image, so that I don't have to create one myself on the local filesystem in case I'm not running it on an RPi? 

Thank you

**Comment by Yakouao** [comment]
Thanks for your reply.

I made some search and i think i have a piste : 
All my previous test was with the last release of raspian which is based of BookWorm... and since bookworm there is some change about : 

1. autostart : X11 vs Wayland/Wayfire : This is a significant change in Bookworm with major impact however it does not impact user of the lite images.
At time of writing Wayland is only the default on Pi 4 and Pi 5.13 Earlier models still default to X11.
/etc/xdg/lxsession/LXDE-pi/autostart and 
/home/pi/.config/lxsession/LXDE-pi/autostart are not used by Wayland/Wayfire. Any changes made to these will be ignored.
A similar functionality is provided in the [autostart] section $HOME/.config/wayfire.ini. 
Unlike /etc/xdg/lxsession/LXDE-pi/autostart this is a per user configuration.

2.  Python, Pip, and Venvs : With Bookworm the default python configuration is that modules installed through pip must be 
installed into a virtual environment (A.K.A a venv). There are good reasons for this change and it was imposed upstream of Raspberry Pi Ltd.
Attempt to use pip install or sudo pip install without a venv will result in the following 
message:
error: externally-managed-environment

One question why not use /etc/xdg/lxsession/LXDE-pi/autostart instead of /home/pi/.config/lxsession/LXDE-pi/autostart ?
Is there a method to start directly chromium without charging the desktop ... xinit in bashrc or something else...

Reference : 
`https://github.com/thagrol/Guides` 
`https://reelyactive.github.io/diy/pi-kiosk/` 
`https://forums.raspberrypi.com/viewtopic.php?t=294014`
`https://forums.raspberrypi.com/viewtopic.php?t=133691`

Thanks again

**Comment by jr-k** [comment]
@Yakouao thanks for your digging. What if you `sudo raspi-config` then select `Advanced` > `Wayland` then switch to `x11` ?

**Comment by jr-k** [comment]
@Yakouao https://github.com/jr-k/obscreen/releases/tag/v1.14

**Comment by Yakouao** [comment]
waho what awesome update 👍 
Works like a charm

I try it both on rpi3b+ and rpi4 in system wide (rpi3 is a little bit just for rendering video)
The fix for youtube video works now
Only one thing is that the ip is not showing on the splashcreen (it is showing "unknown ip adress") ?...

Here some features suggestions : 
1. all your script would works only with th pi user ann not if you change the username. So is it possible to replace it with $user or $(whoami) and for the directory /home/pi to ~/ 
2. add a stop date to the scheduler and/or someting like for 1 day, 1 week, 1 month
3. Add a button previous slide and one for next slide in the manage page
4. make the setting page more verbose : rpi model info, free space, memory usage, mac address, os version, the last xxx line of logs,...

Thanks you again

**Comment by jr-k** [comment]
0. IP fix, `obscreen-manager.service` was the issue, you need to replace that file then `sudo systemctl daemon-reload` and `sudo systemctl restart obscreen-manager`.
1. Version 1.14 is up to date and abstract user name.
2. Maybe you can open a new feature request issue ? We really need to close that one, thanks.
3. Same as 2
4. Same as 2
5. Done

Thanks, I'm closing this issue now.
