### ISSUE TITLE
[BUG] Clicking restart loop returns internal server error

### ISSUE THREAD

**Issue by gordnhoo** [jr-k/obscreen#5]
**Describe the bug**
When clicking the restart loop button in the interface an internal server error appears, even though the clients are restarted.

**Hardware:**
 - *Device*:  Raspberry pi 4

**Sofware :**
 - *Obscreen version*: `v2.9.2`
 - *Installation method*:  Docker
 - *Browser*: `Chromium` 
 - *Player method*: `Systemd with obscreen-player.service` 

Error message

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "<frozen src.service.WebServer>", line 128, in decorated_function
  File "<frozen src.controller.SlideController>", line 112, in slideshow_player_refresh
  File "/usr/local/lib/python3.9/site-packages/werkzeug/utils.py", line 554, in redirect
    display_location = html.escape(location)
  File "/usr/local/lib/python3.9/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
AttributeError: 'NoneType' object has no attribute 'replace'
2024-11-29 10:22:36,324 - ERROR - Exception on /slideshow/player-refresh [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "<frozen src.service.WebServer>", line 128, in decorated_function
  File "<frozen src.controller.SlideController>", line 112, in slideshow_player_refresh
  File "/usr/local/lib/python3.9/site-packages/werkzeug/utils.py", line 554, in redirect
    display_location = html.escape(location)
  File "/usr/local/lib/python3.9/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by jr-k** [comment]
Which URL are you on when you click the refresh link?

**Comment by gordnhoo** [comment]
I can't tell you the url exactly today but i'm running obscreen behind a reverse proxy ,maybe it could be because of that ?

**Comment by gordnhoo** [comment]
This the website i get redirected to https://my_obscreen.com:5000/slideshow/player-refresh?next=%2Flogs%3F
The url im on is https://my_obscreen.com:5000

**Comment by jr-k** [comment]
@gordnhoo do you still have this issue with 2.9.10 ?
